### ISSUE TITLE
Problem with make run -> build folder not present in node_modules

### ISSUE THREAD

**Issue by NoZiL** [marmelab/ng-admin-demo#27]
Since today's release of ng-admin, build folder is no longer present in ng-admin, so makefile crashes

```
➜  ng-admin-demo git:(gh-pages) ✗ make run
cp: cannot stat './node_modules/ng-admin/build/ng-admin.min.js': No such file or directory
makefile:10: recipe for target 'copy-ng-admin' failed
make: *** [copy-ng-admin] Error 1
```

**Comment by miguelslemos** [comment]
i have the same problem, someone can help ?

**Comment by miguelslemos** [comment]
@jpetitcolas  could help please?

**Comment by jpetitcolas** [comment]
I'm working on it. It seems we released ng-admin the wrong way (some issues with declared dependencies). Should be fine in following hours.

**Comment by miguelslemos** [comment]
Thanks so much !

**Comment by NoZiL** [comment]
Thanks @jpetitcolas

**Comment by sabliao** [comment]
Is there a branch I should pull for the changes to make this work? I'm still experiencing this error unfortunately.

**Comment by NoZiL** [comment]
You can use the previous ngAdmin version in package.json, like this :
`"ng-admin": "marmelab/ng-admin#v1.0.0-alpha4",`

**Comment by Kmaschta** [comment]
I confirm, the `ng-admin` beta build was broken.
It's fixed with new versions, just type `npm install ng-admin`.

Thanks!

**Comment by onesse** [comment]
Hello, I experienced the same issue today :(
Is it broken again ?
